sudo: false
language: java
jdk:
- oraclejdk8
script:
- test/run.sh
notifications:
  slack:
    secure: cK5dgbXR9TN8s1Abm1LvyPMeQq9S+7K6AII/4nUvf/OZ8Q1r45VslXOzNtgBIQEzTon/LJrYJ5hXNOLz2HNEcj3rnVwfXGsZq/0KYIa5hIPH+HH4jjoGGutiYPoY0qp0nwKCmOKHkmMO6rnWRMBTGThNAIZEwokMAmkN/PRLAiU=
